from django.conf.urls import patterns, include, url

from pki import views

urlpatterns = patterns('',
    url(r'^/$',                               views.list_cert.as_view(), name='index'),
    url(r'/profile/(?P<pk>\d+)/del/$',        views.delete_cert_profile.as_view(), name='profile_delete'),
    url(r'/profile/(?P<pk>\d+)/$',            views.update_cert_profile.as_view(), name='profile_update'),
    url(r'/profile/new/$',                    views.create_cert_profile.as_view(), name='profile_add'),
    url(r'/profile/$',                        views.list_cert_profile.as_view(), name='profile_list'),
    url(r'/cert/(?P<pk>\d+)/del/$',           views.delete_cert.as_view(), name='cert_delete'),
    url(r'/cert/(?P<pk>\d+)/sign/$',          views.sign_cert, name='cert_sign'),
    url(r'/cert/(?P<pk>\d+)/revoke/$',        views.revoke_cert.as_view(), name='cert_revoke'),
    url(r'/cert/(?P<pk>\d+)/download/$',      views.download_cert, name='cert_download'),
    url(r'/cert/(?P<pk>\d+)/send/$',          views.send_cert, name='cert_send'),
    url(r'/cert/(?P<pk>\d+)/$',               views.update_cert.as_view(), name='cert_update'),
    url(r'/cert/new/$',                       views.create_cert.as_view(), name='cert_add'),
    #url(r'/cert/rest/$',                      views.cert_list.as_view()),
    url(r'/cert/rest/(?P<pk>[0-9]+)/$',       views.cert_detail.as_view()),
    url(r'/cert/restapi/(?P<pk>\w+)/$',       views.cert_list.as_view()),
    url(r'/cert/$',                           views.list_cert.as_view(), name='cert_list'),
    url(r'/ca/(?P<pk>\d+)/del/$',             views.delete_ca.as_view(), name='ca_delete'),
    url(r'/ca/(?P<pk>\d+)/sign/$',            views.sign_ca, name='ca_sign'),
    url(r'/ca/(?P<pk>\d+)/$',                 views.update_ca.as_view(), name='ca_update'),
    url(r'/ca/new/$',                         views.create_ca.as_view(), name='ca_add'),
    url(r'/ca/$',                             views.list_ca.as_view(), name='ca_list'),
    #url(r'/(?P<page_id>\d+)/$',               views.list_cert_page.as_view(), name='list'),
    url(r'/ocsp/$',                           views.ocsp_server, name='ocsp'),
    url(r'/enrol/$',                          views.certWizard.as_view()),
    url(r'/rest/(?P<pk>\d+)/del/$',           views.delete_rest.as_view(), name='rest_delete'),
    url(r'/rest/(?P<pk>\d+)/$',               views.update_rest.as_view(), name='rest_update'),
    url(r'/rest/new/$',                       views.create_rest.as_view(), name='rest_add'),
    url(r'/rest/$',                           views.list_rest.as_view(), name='rest_list'),
)
